[project]
name = "ai-plant-monitor"
version = "0.1.0"
description = "Luna AI Plant Care System"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "google-genai>=1.74.0",
    "google-generativeai>=0.8.6",
    "pandas>=3.0.2",
    "pipwin>=0.5.2",
    "pyserial>=3.5",
    "python-dotenv>=1.2.2",
    "pyttsx3>=2.99",
    "requests>=2.33.1",
    "schedule>=1.2.2",
    "vosk>=0.3.45",
]

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["python", "."]   # Important for your project structure

[tool.ruff.lint]
select = [
    "E", "F", "B", "I", "UP", "SIM", "PL", "RUF"
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
